# Generated by Django 5.2.15 on 2026-07-09 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='DAT',
            field=models.DateField(default=datetime.datetime(2026, 7, 9, 18, 56, 5, 77587, tzinfo=datetime.timezone.utc)),
        ),
    ]
