# Generated by Django 5.2.15 on 2026-07-09 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_page_dat'),
    ]

    operations = [
        migrations.CreateModel(
            name='pag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DAT', models.DateField(default=datetime.datetime(2026, 7, 9, 19, 14, 48, 16207, tzinfo=datetime.timezone.utc))),
                ('content', models.TextField(max_length=700)),
            ],
        ),
        migrations.DeleteModel(
            name='page',
        ),
    ]
